spring:
  application:
    name: hellopay
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
jwt:
  issuer: ${spring.application.name}
  expiration:
    access: 900 # 15 minutes
    refresh: 604800 # 7 days
  keys:
    private-key: ${JWT_PRIVATE_KEY}
    public-key: ${JWT_PUBLIC_KEY}
stripe:
    api-key: ${STRIPE_SECRET_KEY}
    webhooks:
      success: http://localhost:3000/checkout/session/success
      cancel: http://localhost:3000/checkout/session/cancel